// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7tZm3aWBq0DE4uRmtGYVoloqSmUNwfM',
    appId: '1:742374039090:android:c5a99fe9e5b5d25675662b',
    messagingSenderId: '742374039090',
    projectId: 'himachalirishtawebapi',
    databaseURL: 'https://himachalirishtawebapi-default-rtdb.firebaseio.com',
    storageBucket: 'himachalirishtawebapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFWl3_BO2Zpc3wJa72X_BDYxAV02hH3R8',
    appId: '1:742374039090:ios:acf9c87cc9b4119575662b',
    messagingSenderId: '742374039090',
    projectId: 'himachalirishtawebapi',
    databaseURL: 'https://himachalirishtawebapi-default-rtdb.firebaseio.com',
    storageBucket: 'himachalirishtawebapi.appspot.com',
    iosClientId: '742374039090-bims8h953ns5aeihlp408m41d63tfmoh.apps.googleusercontent.com',
    iosBundleId: 'com.himachalirishta.test.himachaliRishta',
  );

  static const FirebaseOptions web = FirebaseOptions(apiKey: "AIzaSyASyhy0XVdTZPmN-nEwsE3SZy0J7ZlUJnU",
      authDomain: "himachalirishtawebapi.firebaseapp.com",
      databaseURL: "https://himachalirishtawebapi-default-rtdb.firebaseio.com",
      projectId: "himachalirishtawebapi",
      storageBucket: "himachalirishtawebapi.appspot.com",
      messagingSenderId: "742374039090",
      appId: "1:742374039090:web:d75c74738a221c2f75662b",
      measurementId: "G-ZWRCSMP85M");
}
